Implement survey
CKPI/Survey pull request #12
Opened 2017-12-27 18:47 UTC by nechaido

2017-12-27 20:31 UTC, tshemsedinov reviewed
Почему `gs.connection.select` а не `gs.select` ?

2017-12-28 09:45 UTC, nechaido commented
@tshemsedinov писал как в предыдущих наших проектах.

2017-12-28 22:11 UTC, tshemsedinov approved these changes
Давай так, потом разберусь, зарефакторим

2017-12-31 14:07 UTC, belochub requested changes

2017-12-31 14:07 UTC, belochub commented on applications/survey/api/survey/getSurveys.js
> +  function sendSurveys(error, survays) {
Опечатка в слове 'surveys'.

2017-12-31 14:07 UTC, belochub commented on applications/survey/api/survey/answer.js
> +  if (typeof surveyId !== 'number' && typeof questionIndex === 'number') {
Почему если тип `questionIndex` будет числом, возвращается ошибка?

2017-12-31 14:07 UTC, belochub commented on doc/collections.md
>    student: 'id',
В коде это поле называется `studentId`, тут тоже стоит поменять.

2017-12-31 14:07 UTC, belochub commented on applications/survey/api/survey/answer.js
> +        userResponse.answers = [];
Тут лучше создать сразу массив заполненный значениями `null`, чтобы избежать возможного использования sparse массива, кажется мы это обсуждали.

2017-12-31 14:07 UTC, belochub commented on applications/survey/api/survey/answer.js
> +      if (questionsAnswered === survey.questions.length) {
Учитывая комментарий к строке 51 этого файла, строки 61-66 можно будет заменить на
```javascript
userResponse.completed = userResponse.answers.every(element => !!element);
```

2017-12-31 14:07 UTC, belochub commented on applications/survey/api/survey/answer.js
> +        submit = gs.connection.create;
Скорее всего здесь не хватает `bind`'а, должно быть
```javascript
submit = gs.connection.create.bind(gs.connection);
```

2017-12-31 14:07 UTC, belochub commented on applications/survey/api/survey/answer.js
> +        submit = gs.connection.update;
То же самое здесь по поводу `bind`'а.

2017-12-31 14:07 UTC, belochub commented on applications/survey/api/survey/answer.js
> +  fetchSurvey();
Не обязательно было выносить `gs.connection.select` в эту функцию, это только увеличило индентацию для callback'а в нём, и это не несёт практической пользы.

2017-12-31 14:07 UTC, belochub commented on applications/survey/api/survey/getQuestions.js
> +  fetchSurvey();
То же самое по поводу вынесения в функцию.

2017-12-31 14:07 UTC, belochub commented on doc/api.md
> +questions = {
Тут невалидный объект получается, непонятна структура.

2017-12-31 14:07 UTC, belochub commented on applications/survey/api/survey/getSurveys.js
> +      callback(api.jstp.ERR_INTERNAL_API_ERROR);
В эту функцию уже возвращается `jstp` ошибка, почему просто не вернуть её в `callback`?

2017-12-31 14:07 UTC, belochub commented on doc/api.md
> +questions = {
Пока непонятно, в каком формате будут возвращаться вопросы, поэтому я пока пропустил в ревью логику метода `getQuestions`.

2017-12-31 14:07 UTC, belochub commented on applications/survey/api/survey/getSurveys.js
> +        surveyInfo.completed = response.completed;
Получается, что если `!response === true`, поле `surveyInfo.completed` будет равно `undefined`, а в описании возвращаемого значения там указан тип `'boolean'`.

2017-12-31 14:07 UTC, belochub commented on doc/api.md
> +  completed: 'bool',
Лучше будет заменить `'bool'` на `'boolean'`.

2017-12-31 14:07 UTC, belochub commented on doc/collections.md
>    completed: 'bool',
Здесь тоже лучше будет исправить название типа на `'boolean'`, к сожалению, ранее не обратил на это внимание.

2018-01-02 14:09 UTC, nechaido commented on applications/survey/api/survey/answer.js
> +        submit = gs.connection.create;
Я использую `call` при вызове.

2018-01-02 14:09 UTC, nechaido commented on applications/survey/api/survey/answer.js
> +        submit = gs.connection.update;
Я использую `call` при вызове.

2018-01-02 14:12 UTC, belochub commented on applications/survey/api/survey/answer.js
> +        submit = gs.connection.create;
Окей, поэтому я и сказал "скорее всего", не был уверен.

2018-01-02 14:22 UTC, nechaido commented on applications/survey/api/survey/getSurveys.js
> +      callback(api.jstp.ERR_INTERNAL_API_ERROR);
Тогда код ошибки будет `1`, а `ERR_INTERNAL_API_ERROR = 16`.

2018-01-02 14:24 UTC, belochub commented on applications/survey/api/survey/getSurveys.js
> +      callback(api.jstp.ERR_INTERNAL_API_ERROR);
Почему `1`?

2018-01-02 14:29 UTC, nechaido commented on applications/survey/api/survey/getSurveys.js
> +      callback(api.jstp.ERR_INTERNAL_API_ERROR);
```
RemoteError.getJstpArrayFor = function(error) {
  if (error instanceof RemoteError) {
    return error.toJstpArray();
  } else if (Array.isArray(error)) {
    return error;
  } else if (typeof(error) === 'number') {
    return [error];
  } else if (typeof(error) === 'string') {
    return [1, error];
  } else {
    return [1, error.toString()];
  }
};
```

2018-01-02 14:30 UTC, belochub commented on applications/survey/api/survey/getSurveys.js
> +      callback(api.jstp.ERR_INTERNAL_API_ERROR);
Ну так, согласно этому коду будет не `1`, почему ты говоришь, что будет `1`?

2018-01-02 15:05 UTC, nechaido commented on applications/survey/api/survey/getSurveys.js
> +      callback(api.jstp.ERR_INTERNAL_API_ERROR);
Я ошибся, я думал что там будет не `RemoteError`.

2018-01-02 15:58 UTC, belochub commented on doc/api.md
> +  questions = [{
Почему здесь используется знак `=` вместо `:`?

2018-01-02 16:04 UTC, belochub commented on doc/api.md
> +  answers = [
Может было бы лучше возвращать не отдельно массив ответов пользователя, а добавить поле с названием `userAnswer`, `studentAnswer` или `givenAnswer` в каждый объект в массиве `questions`?
Тогда можно было бы вернуться к прошлому формату возвращаемого значения, когда `getQuestions` возвращает массив объектов `Question`, и мне кажется, это немного упростило бы обработку результата вызова на клиентской стороне.

2018-01-04 14:05 UTC, tshemsedinov commented
Давайте не делать таких огромных PR, мерджить побыстрее и открывать новые

2018-01-04 15:19 UTC, belochub commented on doc/api.md
> +question = [{
Здесь, насколько я понимаю, не должно быть массива, только объект.

2018-01-04 15:45 UTC, belochub commented on doc/api.md
>    id: 'string',
Тут `id` будет возвращаться типа `number`.

2018-01-04 15:45 UTC, belochub commented on doc/collections.md
>    surveyId: 'string',
Тут тип будет `'number'`.

2018-01-04 15:45 UTC, belochub commented on doc/collections.md
> +  studentId: 'string',
И тут тип будет `'number'`.

2018-01-04 15:45 UTC, belochub commented on applications/survey/api/survey/answer.js
> +    submitResponse(userResponse, survey);
Я думаю тут перед этим вызовом нужно еще проверить, является ли данный `survey` доступным для текущего студента, и если нет, то также возвращать `ERR_SURVEY_NOT_FOUND`.
Но так как это не срочно необходимо, предлагаю сделать это в отдельном PR.

2018-01-04 15:45 UTC, belochub commented on applications/survey/api/survey/getQuestions.js
> +    fetchResponse(survey);
Я думаю тут тоже перед этим вызовом нужно еще проверить, является ли данный `survey` доступным для текущего студента, и если нет, то также возвращать `ERR_SURVEY_NOT_FOUND`.
Но так как это не срочно необходимо, предлагаю сделать это в отдельном PR.

2018-01-04 15:45 UTC, belochub commented on applications/survey/api/survey/answer.js
> +    submitResponse(userResponse, survey);
Также перед этим вызовом нужно будет в одном из следующих PR добавить валидацию объекта `answer` на соответствие типу вопроса, и возвращать ошибку `ERR_INVALID_ANSWER`, которая на данный момент нигде не используется.

2018-01-04 16:10 UTC, belochub approved these changes

2018-01-04 16:10 UTC, merged