Implemented schedule.js
CKPI/Survey pull request #19
Opened 2018-01-10 00:41 UTC by o-rumiantsev

2018-01-10 02:37 UTC, tshemsedinov requested changes

2018-01-10 02:37 UTC, tshemsedinov commented on applications/survey/lib/schedule.js
> +      let rawData = '';
Лучше массив, а потом делаем `rawData.join('')`

2018-01-10 02:37 UTC, tshemsedinov commented on applications/survey/lib/schedule.js
> +        setTimeout(() => {
Зачем этот setTimeout и почему именно 100?

2018-01-10 02:37 UTC, tshemsedinov commented on applications/survey/lib/schedule.js
> +  const https = require('https');
Нельзя использовать `require` в impress, все нужные модули уже подгружены в неймспейсы, например `api.https`

2018-01-10 02:37 UTC, tshemsedinov commented on applications/survey/lib/schedule.js
> +    const url = 'https://api.rozklad.org.ua/v2/teachers/' + filter;
Нужно выделить общую часть URL `https://api.rozklad.org.ua/v2/teachers` в отдельную константу и потом ее использовать в разных местах чтобы исключить дублирование

2018-01-10 02:37 UTC, tshemsedinov commented on applications/survey/lib/schedule.js
> +      let rawData = '';
См. похожий коммент, лучше `[].join('')`

2018-01-10 02:37 UTC, tshemsedinov commented on applications/survey/lib/schedule.js
> +        if (teachers.length === 100) getTeachers(offset);
Что такое 100 тут? Может сделаем константу, имя которой будет объяснять значение 100

2018-01-10 02:37 UTC, tshemsedinov commented on applications/survey/lib/schedule.js
> +        ), offset * 50);
Почему setTimeout и почему 50?

2018-01-10 02:37 UTC, tshemsedinov commented on applications/survey/lib/schedule.js
> +    const url = `https://api.rozklad.org.ua/v2/teachers/${teacherName}/lessons`;
См. коммент о выделении URL

2018-01-10 06:33 UTC, o-rumiantsev commented on applications/survey/lib/schedule.js
> +        if (teachers.length === 100) getTeachers(offset);
100 это максимальное колличество преподов в респонсе, по этому с каждым запросом смещение нужно увеличивать на 100, чтобы пройти по всем преподам. проверка на длинну массива преподов в респонсе зделана для того, чтобы мы знали, когда получили последнюю страницу(с нее скорее всего придет меньше чем 100 преподов)

2018-01-10 06:41 UTC, o-rumiantsev commented on applications/survey/lib/schedule.js
> +        ), offset * 50);
setTimeout с целью избежания ошибоки, связанной с превышением лимита отправляемых запросов. Получается что мы на каждый приходимый респонс о преподах(которых 100 штук в онсновном) сразу посылаем для каждого запрос на пары, которые он ведет. Так как новые преподы приходят довольно быстро, то в интоге слишком много одновременно отправленных запросов. По этому я решил сделать небольшую задержку для каждого цыкла. offset * 50 потому что оффсэт постоянно меняется на 100, и интервалы получаются одинаковые(0 сек, 5 сек, 10 сек и тд). 50 потому что это минимальное значение с которым мне не выдало ошибку привешения лимита.

2018-01-10 06:52 UTC, o-rumiantsev commented on applications/survey/lib/schedule.js
> +        setTimeout(() => {
этот setTimeout стоит, потому что респонсы некоторые приходят одновременно, по этому проверка длинны очереди происходит некорректо, если ее производить именно в момент получения респонса., по этому я поставил небольшую задержку. 100, конечно много как то, нужно уменьшить, но я не знаю как обьяснить почему именно столько

2018-01-10 23:47 UTC, tshemsedinov commented on applications/survey/lib/schedule.js
> +        if (teachers.length === 100) getTeachers(offset);
Ну это пейджин зовется. значит `const ITEMS_PER_PAGE = 100;`

2018-01-10 23:48 UTC, tshemsedinov commented on applications/survey/lib/schedule.js
> +        setTimeout(() => {
@belochub @nechaido объясните как и почему нужно переделать

2018-01-12 12:57 UTC, nechaido requested changes

2018-01-12 12:57 UTC, nechaido commented on applications/survey/lib/schedule.js
> +  const https = api.https;
Это не нужно запоминать в отдельную переменную.

2018-01-12 12:57 UTC, nechaido commented on applications/survey/lib/schedule.js
> +  const metasync = api.metasync;
Тут тоже.

2018-01-12 12:57 UTC, nechaido commented on applications/survey/lib/schedule.js
> +    const url = rozkladApiTeachers + filter;
Это инфарианта, вынеси ее из функции в константы.

2018-01-12 12:57 UTC, nechaido commented on applications/survey/lib/schedule.js
> +        teachers.forEach(
Лучше поменять на `reduce`.

2018-01-12 12:57 UTC, nechaido commented on applications/survey/lib/schedule.js
> +    const url = rozkladApiTeachers + teacherName + '/lessons';
ТОже вынести в констатну типа `URL_TEACHER_LESSONS`.

2018-01-12 12:57 UTC, nechaido commented on applications/survey/lib/schedule.js
> +      const rawData = [];
Нужно добавить проверку кода ответа.

2018-01-12 15:57 UTC, tshemsedinov approved these changes
Можно конечно нейминг улучшить, например `fill` это очень общее название, но в общем ок

2018-01-17 14:47 UTC, belochub commented on applications/survey/lib/schedule.js
> +    url.search = `?filter={"offset":${offset}}`;
Тут, для задания параметров, используй свойство `searchParams`, вместо `search`.

2018-01-19 14:15 UTC, belochub approved these changes

2018-01-19 14:15 UTC, nechaido approved these changes

2018-01-19 14:21 UTC, belochub commented
Landed in https://github.com/CKPI/Survey/commit/561af1282ab63c1849a5ad82e0749f36703db261.

2018-01-19 14:21 UTC, closed without merging