Add CSVConverter and test for it
CKPI/Survey pull request #7
Opened 2017-12-19 19:51 UTC by SemenchenkoVitaliy

Please, let me know if there should be reverse converter and give an example of how tests should be written

2017-12-20 11:19 UTC, tshemsedinov approved these changes
Будем считать, что заголовков в csv нет

2017-12-20 11:21 UTC, tshemsedinov requested changes
Пройдись линтером по коду, там куча всего. @nechaido помоги если что

2017-12-20 12:09 UTC, nechaido requested changes
Имена полей в структурах должны быть в camelCase.
Как было сказано в https://github.com/CKPI/Survey/issues/1#issuecomment-353031874, разделителем будет ';'. Даты должны быть конвертированны в тип 'Date`. Я бы предпочел, чтобы результирующий документ был структурированным, @tshemsedinov что скажешь?
Есть вот такая реализация:
```js
const transformations = {
  string: (entry) => entry,
  number: (entry) => +entry,
  date: (entry) => new Date(entry),
};

const field = (name, type) => {
  if (!type) {
    type = 'string'
  }
  return { name, type };
};

const fields = [
  field('firstName'),
  field('lastName'),
  field('middleName'),
  field('born', 'date'),
  field('ipn'),
  field('documentType'),
  field('passportSeries'),
  field('passportNumber', 'number'),
  field('passportDate', 'date'),
  field('passportDepartment'),
  field('studentCardId'),
  field('studentCardSeries'),
  field('studentCardNumber', 'number'),
  field('studentCardCreationDate', 'date'),
  field('studentCardEolDate', 'date'),
  field('faculty'),
  field('courseId', 'number'),
  field('group'),
];

const structurizeStudent = (student) => {
  return {
    name: {
      first: student.firstName,
      last: student.lastName,
      middle: student.middleName,
    },
    born: student.born,
    ipn: student.ipn,
    passport: {
      type: student.documentType,
      series: student.passportSeries,
      created: student.passportDate,
      department: student.passportDepartment,
    },
    studentCard: {
      id: student.studentCardId,
      series: student.studentCardSeries,
      number: student.studentCardNumber,
      created: student.studentCardCreationDate,
      eol: student.studentCardEolDate,
    },
    faculty: student.faculty,
    course: student.courseId,
    group: student.group,
  }
}

const parseLine = (line) => {
  const entries = line.split(',');
  const student = {};
  fields.forEach((field, index) => {
    student[field.name] = transformations[field.type](entries[index]);
  });
  return structurizeStudent(student);
}

module.exports = {
  parseLine,
};
```

2017-12-20 12:18 UTC, tshemsedinov commented
@nechaido да, все в типы переводим

2017-12-20 12:22 UTC, nechaido commented
@tshemsedinov я спрашивал о структуризации обьекта `student`.

2017-12-20 14:10 UTC, tshemsedinov commented
@nechaido да, это удобно :+1:

2017-12-21 00:12 UTC, tshemsedinov requested changes

2017-12-21 00:12 UTC, tshemsedinov commented on lib/CSVConverter.js
> +  string: (entry) => entry,
Функция `id` лучше выглядит без скобок `entry => entry`

2017-12-21 00:12 UTC, tshemsedinov commented on lib/CSVConverter.js
> +    type = 'string';
Лучше `type = type || 'string';`

2017-12-21 00:12 UTC, tshemsedinov commented on lib/CSVConverter.js
> +  return { name, type };
А целиком лучше так:
```
const field = (name, type) => { name, type: type || 'string' };
```

2017-12-21 00:12 UTC, tshemsedinov commented on lib/CSVConverter.js
> +];
`['firstName', 'lastName', ...].map(field)`

2017-12-21 00:12 UTC, tshemsedinov commented on lib/CSVConverter.js
> +  const entries = line.split(';').map((entry) => (entry.trim()));
поменьше скобок `.map(entry => entry.trim());`

2017-12-21 00:12 UTC, tshemsedinov commented on lib/CSVConverter.js
> +    student[field.name] = transformations[field.type](entries[index]);
сложная конструкция, сделайте промежуточные переменные

2017-12-21 00:12 UTC, tshemsedinov commented on tests/CSVConvert.js
> +  passport:
поле `name` имеет другое форматирование, чем `passport`

2017-12-21 00:12 UTC, tshemsedinov commented on tests/CSVConvert.js
>      switch (typeof(expected)) {
`typeof(expected)` вычисляется несколько раз, положите в промежуточную переменную и `switch` в этом случае лучше заменить на `if`

2017-12-21 00:12 UTC, tshemsedinov commented on tests/CSVConvert.js
>            } else {
не нужно делать `else` тут вообще, просто после блока `if` еще один `return` и в него попадет все, что под условие `if` не подошло

2017-12-21 00:12 UTC, tshemsedinov commented on tests/CSVConvert.js
> +    if (results.reduce((acc, cur) => (acc && cur)))
а тут лучше скобочек `{}` наставить

2017-12-21 10:52 UTC, tshemsedinov approved these changes

2017-12-21 11:07 UTC, nechaido requested changes

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +  born: new Date(1 / 1 / 1990),
This should be `'1/1/1990'` instead of `1 / 1 / 1990`.

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +    created: new Date(1 / 1 / 2000),
Ditto.

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +    created: new Date(9 / 1 / 2009),
Ditto.

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +    eol: new Date(6 / 30 / 2013)
Ditto.

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +  born: new Date(1 / 1 / 1990),
Ditto.

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +    created: new Date(1 / 1 / 2000),
Ditto.

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +    created: new Date(9 / 1 / 2009),
Ditto.

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +    eol: new Date(6 / 30 / 2013)
Ditto.

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +  born: new Date(1 / 1 / 1990),
Ditto.

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +    created: new Date(1 / 1 / 2000),
Ditto.

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +    created: new Date(9 / 1 / 2009),
Ditto.

2017-12-21 11:07 UTC, nechaido commented on tests/CSVConvert.js
> +    eol: new Date(6 / 30 / 2013)
Ditto.

2017-12-21 14:01 UTC, nechaido commented
@SemenchenkoVitaliy сделай ребейз на `master`, модуль перенеси в `/applications/Survey/lib/`, тесты перенеси в `test/unit/`. Для тестирования используй `tap`. Пиши, если нужна будет помощь. Пример модуля оформления можешь найти [сдесь](https://github.com/metarhia/server/blob/master/applications/metarhia.com/lib/metacom.js).

2017-12-21 18:51 UTC, SemenchenkoVitaliy commented
Я додав тести в test/unit. Мені варто додати "tap ./test/unit" в package.json чи перенести тести в tests/unit? Чи потрібно тестувати всі функції і чи варто виділити допоміжні функції в окремий файл?

2017-12-26 17:52 UTC, nechaido commented
@SemenchenkoVitaliy извини за долгий ответ

2017-12-26 17:55 UTC, nechaido commented
@SemenchenkoVitaliy извини за поздний ответ:
1. Пока у нас нет хорошего варината, как расположить их, пожтому пока игнорируем их.
2. Функции не нужно экспортировать, их нужно лишь положить в `api.survey`, impress сам сделает ихдоступными по этой переменной.
3. Не нужно.
4. Все правильно.

2017-12-26 17:57 UTC, nechaido requested changes

2017-12-26 17:57 UTC, nechaido commented on applications/Survey/lib/CSVConverter.js
> +const api = {};
`api` будет добавлен в область видимости при загрузке этого файла, не нужно создавать его.

2017-12-26 17:57 UTC, nechaido commented on applications/Survey/lib/CSVConverter.js
> +api.transformations = {
Эту функцию не нужно экспортировать.

2017-12-26 17:57 UTC, nechaido commented on applications/Survey/lib/CSVConverter.js
> +api.typify = (field) => ({
Эту функцию не нужно экспортировать.

2017-12-26 17:57 UTC, nechaido commented on applications/Survey/lib/CSVConverter.js
> +api.structurizeStudent = (student) => ({
Эту функцию не нужно экспортировать.

2017-12-26 17:57 UTC, nechaido commented on applications/Survey/lib/CSVConverter.js
> +module.exports = api;
Эта строка не нужна.

2017-12-28 12:11 UTC, nechaido commented on applications/Survey/lib/CSVConverter.js
> +    created: student.passportDate,
Переименуй это поле в `issued`.

2017-12-28 12:11 UTC, nechaido commented on applications/Survey/lib/CSVConverter.js
> +    created: student.studentCardCreationDate,
Переименуй это поле в `issued`.

2017-12-28 12:11 UTC, nechaido commented on applications/Survey/lib/CSVConverter.js
> +    eol: student.studentCardEolDate,
Переименуй это поле в `expires`.

2017-12-28 12:12 UTC, nechaido commented on tests/unit/CSVConverter.js
> +/*
Удали закомментированный код.

2017-12-28 12:14 UTC, nechaido commented on applications/Survey/lib/CSVConverter.js
> +api.survey.parseLine = (line) => {
Помести это в `api.survey.csv`.

2017-12-28 12:14 UTC, nechaido commented on applications/Survey/lib/CSVConverter.js
> +api.survey.parseCSV = (text) => {
Помести это в `api.survey.csv`.

2017-12-28 12:15 UTC, nechaido commented
@SemenchenkoVitaliy поправишь то, что я откомментировал и будем сливать в мастер.

2017-12-28 14:01 UTC, belochub commented on applications/Survey/lib/CSVConverter.js
> +const api.survey.csv = {};
Ошибка синтаксиса в данной строке.

2017-12-28 14:02 UTC, belochub commented on tests/unit/CSVConverter.js
> +    department: 'Київським МВ УМВС' },
Думаю, стоит добавить перенос строки перед `}`.

2017-12-28 14:07 UTC, belochub commented on tests/unit/CSVConverter.js
> +const compare = (expected, recieved) => {
В `tap` есть встроенная функция для глубокого сравнения объектов, стоит использовать её.

2017-12-28 14:23 UTC, nechaido commented on tests/unit/CSVConverter.js
> +const compare = (expected, recieved) => {
`tap.strictSame`

2017-12-28 15:47 UTC, SemenchenkoVitaliy commented
Якого виду повинні бути тести?
1. https://github.com/metarhia/impress/tree/master/tests/unittests
2. https://github.com/metarhia/jstp/tree/master/test/node

2017-12-28 19:21 UTC, SemenchenkoVitaliy commented
Даний варіант буде коректним, якщо impress зробить api видимим у межах tests/unit/CSVConverter.js

2017-12-29 10:54 UTC, nechaido commented on applications/Survey/lib/CSVConverter.js
> +api.survey.csv = {};
Поставь перед этим:
```js
if (!api.survey) {
  api.survey = {};
}
```

2017-12-29 10:56 UTC, nechaido commented
@SemenchenkoVitaliy сейчас `impress` не поддерживает тестирование прикладного кода, поэтому тесты оставим как есть, а когда необходимый функционал появится - я мы их обновим.

2017-12-29 11:57 UTC, SemenchenkoVitaliy commented
В такому випадку для роботи тестів доведеться додати  
if (!global.api) {
  global.api = {};
  module.exports = api;
}

2017-12-31 11:35 UTC, nechaido approved these changes

2017-12-31 11:45 UTC, belochub commented on applications/Survey/lib/CSVConverter.js
> +  if (lines.length === 0) return [];
Тут лишняя проверка, она никак не влияет на результат.

2017-12-31 11:50 UTC, belochub commented on applications/Survey/lib/CSVConverter.js
> +    student[field.name] = transformation(entry);
Можно было бы здесь еще возвращать/выбрасывать ошибку, когда данные на вход не являются валидными, допустим, не соотвествуют ожидаемому типу.

2017-12-31 12:14 UTC, SemenchenkoVitaliy commented on applications/Survey/lib/CSVConverter.js
> +    student[field.name] = transformation(entry);
Для перевірки, чи можна перетворити string у number - не проблема. Але для перевірди корректності дати доведеться використовувати regex типу такого, що зменшить швидкість:
/\d{4}\/\d{2}\/\d{2}/.test(str)
Чи доречним є використання цього?

2017-12-31 12:16 UTC, belochub commented on applications/Survey/lib/CSVConverter.js
> +    student[field.name] = transformation(entry);
Зачем использовать регулярные выражения, когда в JavaScript уже встроен парсер даты/времени?
Тем более, данное регулярное выражение неправильно проверяет валидность даты.

2017-12-31 13:04 UTC, SemenchenkoVitaliy commented on applications/Survey/lib/CSVConverter.js
> +    student[field.name] = transformation(entry);
Да, трохи затупив

2017-12-31 13:07 UTC, belochub commented on applications/Survey/lib/CSVConverter.js
> +    if (field.type === 'date' && isNaN(student[field.name].getTime()))
Не обязательно вызывать метод `getTime` на дате перед передачей её в `isNaN`.

2017-12-31 13:12 UTC, SemenchenkoVitaliy commented
Пофіксив

2017-12-31 13:14 UTC, belochub approved these changes

2018-01-02 15:09 UTC, nechaido commented
@SemenchenkoVitaliy объедини это все в оддин коммит и я солью его в мастер.

2018-01-04 12:03 UTC, nechaido commented
@SemenchenkoVitaliy Переименуй, пожалуйста, коммит в `Add CSVConeverter`.

2018-01-04 12:18 UTC, SemenchenkoVitaliy commented
Зробив

2018-01-04 12:22 UTC, merged

2018-01-04 12:24 UTC, nechaido commented
@SemenchenkoVitaliy Спасибо за твой вклад, извини за долгий процесс.